version: '3.1'

services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: "crudlaravel"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - '3308:3306'
    volumes:
      - ./mysql:/var/lib/mysql
